--- 
- 
  become: true
  hosts: all
  name: "install and start apache"
  tasks: 
    - name: "httpd package is present"
      yum: 
        name: httpd
        state: latest
    - name: "latest index.html file is present"
      template: 
        dest: /var/www/html/
        src: files/index.html
    - name: "httpd is started"
      service: 
        name: httpd
        state: started
