--- 
- 
  become: true
  hosts: all
  name: "install and start apache"
  tasks: 
    - name: "httpd package is present"
      yum: 
        name: httpd
        state: latest
    - name: "httpd is started"
      service: 
        name: httpd
        state: started
