--- 
- 
  become: true
  hosts: all
  name: "install and start apache"
  tasks: 
    - name: "httpd package is present"
      yum: 
        name: httpd
        state: latest
    - name: Make certain httpd listens on a free port
      lineinfile: dest=/etc/httpd/conf/httpd.conf regexp="^Listen 80" line="Listen 81" state=present
    - name: "httpd is started"
      service: 
        name: httpd
        state: started
